### ISSUE TITLE
Current Solution not working

### ISSUE THREAD

**Issue by kent50** [chadrickman/PizzaPlanet#5]
I wasn't sure if you guys were aware, but the current updated file has some errors pertaining to a missing file. I get a compilation error saying "Error	Source file 'TabControl.cs' could not be found." I've re-downloaded the zip and still the same. Of course you guys could have mentioned it and I totally missed it, just let me know.

**Comment by evan686z** [comment]
Ya probably what I added. Altered and created a new tab control class. I'll try to see why it didn't commit correctly when I am able.
